import os
import sys
import io
from datetime import datetime

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether, HRFlowable
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))
        # Header (pages after page 1)
        if self._pageNumber > 1:
            self.drawString(40, 755, "HackZen Platform — Central Analytics & Intelligence Report")
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(40, 747, 572, 747)
        # Footer
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(572, 25, page_text)
        self.drawString(40, 25, "CONFIDENTIAL & PROPRIETARY — GENERATED BY HACKZEN PLATFORM")
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(40, 35, 572, 35)
        self.restoreState()


def build_sample_data():
    return {
        "metadata": {
            "title": "HackZen Platform Analytics & Intelligence Report",
            "generatedAt": datetime.now().strftime("%B %d, %Y at %I:%M %p"),
            "dateRange": "Last 30 Days",
            "hackathon": "All Events",
            "college": "All Colleges",
            "role": "All Roles"
        },
        "kpis": [
            {"metric": "Total Registered Users", "val": "1,248", "change": "+12.4%", "status": "Positive"},
            {"metric": "Live / Running Hackathons", "val": "4", "change": "+2", "status": "Positive"},
            {"metric": "Completed Hackathons", "val": "12", "change": "+4", "status": "Positive"},
            {"metric": "Pending Approvals", "val": "17", "change": "Action Needed", "status": "Attention"},
            {"metric": "Active Registered Teams", "val": "324", "change": "+8.7%", "status": "Positive"},
            {"metric": "Project Submissions", "val": "3,842", "change": "+18.2%", "status": "Positive"},
            {"metric": "Verifiable Certificates Minted", "val": "1,126", "change": "+31.0%", "status": "Positive"},
            {"metric": "Platform API & Service Uptime", "val": "99.98%", "change": "100% Target", "status": "Healthy"}
        ],
        "hackathons": [
            {"rank": "#1", "name": "Global AI Summit 2026", "participants": 642, "submissions": 480, "completion": "88%"},
            {"rank": "#2", "name": "CyberKnights Shield", "participants": 412, "submissions": 310, "completion": "82%"},
            {"rank": "#3", "name": "EcoTech Green Sprint", "participants": 389, "submissions": 295, "completion": "79%"},
            {"rank": "#4", "name": "FinTech DeFi Challenge", "participants": 290, "submissions": 210, "completion": "74%"}
        ],
        "roles": [
            {"role": "Students", "percentage": "78.0%", "count": 973},
            {"role": "Mentors", "percentage": "12.0%", "count": 150},
            {"role": "Organizers", "percentage": "7.0%", "count": 87},
            {"role": "Admins", "percentage": "3.0%", "count": 38}
        ],
        "colleges": [
            {"college": "ABC Engineering College", "students": 340},
            {"college": "VIT Chennai", "students": 280},
            {"college": "SRM Institute of Science & Tech", "students": 210},
            {"college": "IIT Madras", "students": 165},
            {"college": "Anna University", "students": 120}
        ],
        "techStack": [
            {"tech": "React / Next.js", "count": 480},
            {"tech": "Python / PyTorch", "count": 390},
            {"tech": "Node.js / Express", "count": 310},
            {"tech": "FastAPI / MongoDB", "count": 260},
            {"tech": "Solidity / Web3", "count": 140}
        ],
        "timeline": [
            {"week": "Week 1", "submissions": 340, "evaluated": 280},
            {"week": "Week 2", "submissions": 820, "evaluated": 710},
            {"week": "Week 3", "submissions": 1450, "evaluated": 1200},
            {"week": "Week 4", "submissions": 2840, "evaluated": 2300}
        ],
        "mentors": [
            {"rank": "#1", "name": "Ananya Rao", "company": "Microsoft", "sessions": 28, "rating": "4.9 / 5.0"},
            {"rank": "#2", "name": "Priya Sharma", "company": "Google", "sessions": 24, "rating": "4.8 / 5.0"},
            {"rank": "#3", "name": "Kumar S", "company": "Amazon", "sessions": 21, "rating": "4.7 / 5.0"},
            {"rank": "#4", "name": "Rohan Verma", "company": "ProEduvate", "sessions": 18, "rating": "4.6 / 5.0"}
        ],
        "aiAndCerts": {
            "aiQueries": "14,280",
            "uniqueAiUsers": "1,040",
            "avgAiLatency": "1.1s",
            "aiHelpfulRate": "94.2%",
            "certsMinted": "1,126",
            "certsDownloaded": "892",
            "certsVerified": "640",
            "certsRevoked": "2"
        },
        "security": {
            "failedLogins": "14",
            "blockedIps": "2",
            "avgApiLatency": "42ms",
            "cpuLoad": "18%",
            "memoryUsage": "34%",
            "serverUptime": "99.98%"
        }
    }

def generate_pdf_bytes(data: dict) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=40,
        rightMargin=40,
        topMargin=45,
        bottomMargin=45
    )

    styles = getSampleStyleSheet()
    
    # Custom Palette
    c_primary = colors.HexColor("#0284C7")      # Sky 600
    c_dark = colors.HexColor("#0F172A")         # Slate 900
    c_text = colors.HexColor("#334155")         # Slate 700
    c_sub = colors.HexColor("#64748B")          # Slate 500
    c_bg_head = colors.HexColor("#0F172A")      # Header bg
    c_alt_row = colors.HexColor("#F8FAFC")      # Slate 50
    c_border = colors.HexColor("#E2E8F0")       # Slate 200

    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=c_dark
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=c_sub
    )

    section_heading = ParagraphStyle(
        'SectionHeading',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor("#FFFFFF")
    )

    meta_label = ParagraphStyle(
        'MetaLabel',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8,
        leading=11,
        textColor=c_dark
    )

    meta_val = ParagraphStyle(
        'MetaVal',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8,
        leading=11,
        textColor=c_text
    )

    cell_bold = ParagraphStyle(
        'CellBold',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8,
        leading=11,
        textColor=c_dark
    )

    cell_text = ParagraphStyle(
        'CellText',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8,
        leading=11,
        textColor=c_text
    )

    cell_header = ParagraphStyle(
        'CellHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#FFFFFF")
    )

    story = []

    # 1. Header Banner
    story.append(Paragraph("HACKZEN EXECUTIVE PLATFORM REPORT", title_style))
    story.append(Spacer(1, 4))
    story.append(Paragraph("Central Analytics, Cross-Module Performance & Intelligence Audit", subtitle_style))
    story.append(Spacer(1, 10))

    # Meta table
    meta = data["metadata"]
    meta_table_data = [
        [
            Paragraph("<b>Generated On:</b>", meta_label), Paragraph(meta["generatedAt"], meta_val),
            Paragraph("<b>Date Range:</b>", meta_label), Paragraph(meta["dateRange"], meta_val)
        ],
        [
            Paragraph("<b>Hackathon Scope:</b>", meta_label), Paragraph(meta["hackathon"], meta_val),
            Paragraph("<b>College Scope:</b>", meta_label), Paragraph(meta["college"], meta_val)
        ],
        [
            Paragraph("<b>Role Scope:</b>", meta_label), Paragraph(meta["role"], meta_val),
            Paragraph("<b>Classification:</b>", meta_label), Paragraph("CONFIDENTIAL / ORGANIZER & ADMIN", meta_val)
        ]
    ]
    meta_table = Table(meta_table_data, colWidths=[90, 176, 90, 176])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F1F5F9")),
        ('BOX', (0, 0), (-1, -1), 0.5, c_border),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 14))

    def make_section_banner(title_text):
        tbl = Table([[Paragraph(f"<b>{title_text.upper()}</b>", section_heading)]], colWidths=[532])
        tbl.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), c_bg_head),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ]))
        return tbl

    # SECTION 1: Key Platform KPIs
    story.append(make_section_banner("1. Executive Summary & Core Platform KPIs"))
    story.append(Spacer(1, 6))

    kpi_rows = [[
        Paragraph("<b>Metric / Indicator</b>", cell_header),
        Paragraph("<b>Value</b>", cell_header),
        Paragraph("<b>Trend / Variance</b>", cell_header),
        Paragraph("<b>Health Status</b>", cell_header)
    ]]
    for item in data["kpis"]:
        kpi_rows.append([
            Paragraph(item["metric"], cell_bold),
            Paragraph(item["val"], cell_text),
            Paragraph(item["change"], cell_text),
            Paragraph(f"<b>{item['status']}</b>", cell_text)
        ])
    kpi_tbl = Table(kpi_rows, colWidths=[200, 110, 110, 112])
    kpi_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), c_primary),
        ('GRID', (0, 0), (-1, -1), 0.5, c_border),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, c_alt_row]),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(kpi_tbl)
    story.append(Spacer(1, 14))

    # SECTION 2: Top Hackathons
    story.append(make_section_banner("2. Hackathon & Event Performance Leaderboard"))
    story.append(Spacer(1, 6))

    hack_rows = [[
        Paragraph("<b>Rank</b>", cell_header),
        Paragraph("<b>Hackathon Event</b>", cell_header),
        Paragraph("<b>Participants</b>", cell_header),
        Paragraph("<b>Submissions</b>", cell_header),
        Paragraph("<b>Completion Rate</b>", cell_header)
    ]]
    for h in data["hackathons"]:
        hack_rows.append([
            Paragraph(h["rank"], cell_bold),
            Paragraph(h["name"], cell_text),
            Paragraph(str(h["participants"]), cell_text),
            Paragraph(str(h["submissions"]), cell_text),
            Paragraph(h["completion"], cell_bold)
        ])
    hack_tbl = Table(hack_rows, colWidths=[50, 222, 90, 90, 80])
    hack_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), c_primary),
        ('GRID', (0, 0), (-1, -1), 0.5, c_border),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, c_alt_row]),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(hack_tbl)
    story.append(Spacer(1, 14))

    # SECTION 3: User Demographics & Colleges
    story.append(make_section_banner("3. Demographics & Institutional Breakdown"))
    story.append(Spacer(1, 6))

    # Two side-by-side tables: Roles and Colleges
    role_rows = [[Paragraph("<b>Role</b>", cell_header), Paragraph("<b>Share</b>", cell_header), Paragraph("<b>Count</b>", cell_header)]]
    for r in data["roles"]:
        role_rows.append([
            Paragraph(r["role"], cell_bold),
            Paragraph(r["percentage"], cell_text),
            Paragraph(str(r["count"]), cell_text)
        ])
    role_tbl = Table(role_rows, colWidths=[100, 75, 75])
    role_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), c_primary),
        ('GRID', (0, 0), (-1, -1), 0.5, c_border),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, c_alt_row]),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))

    col_rows = [[Paragraph("<b>Top Institution / College</b>", cell_header), Paragraph("<b>Students</b>", cell_header)]]
    for c in data["colleges"]:
        col_rows.append([
            Paragraph(c["college"], cell_text),
            Paragraph(str(c["students"]), cell_bold)
        ])
    col_tbl = Table(col_rows, colWidths=[200, 72])
    col_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), c_primary),
        ('GRID', (0, 0), (-1, -1), 0.5, c_border),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, c_alt_row]),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))

    side_by_side = Table([[role_tbl, col_tbl]], colWidths=[255, 277])
    side_by_side.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 0),
        ('RIGHTPADDING', (0, 0), (-1, -1), 0),
        ('TOPPADDING', (0, 0), (-1, -1), 0),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
    ]))
    story.append(side_by_side)
    story.append(Spacer(1, 14))

    # SECTION 4: Submissions, Tech Stack, Mentors & System
    story.append(make_section_banner("4. Teams, Submissions & Tech Stack Popularity"))
    story.append(Spacer(1, 6))

    time_rows = [[Paragraph("<b>Timeline</b>", cell_header), Paragraph("<b>Submissions</b>", cell_header), Paragraph("<b>Evaluated</b>", cell_header)]]
    for t in data["timeline"]:
        time_rows.append([
            Paragraph(t["week"], cell_bold),
            Paragraph(str(t["submissions"]), cell_text),
            Paragraph(str(t["evaluated"]), cell_text)
        ])
    time_tbl = Table(time_rows, colWidths=[90, 80, 80])
    time_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), c_primary),
        ('GRID', (0, 0), (-1, -1), 0.5, c_border),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, c_alt_row]),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))

    tech_rows = [[Paragraph("<b>Technology / Framework</b>", cell_header), Paragraph("<b>Usage Count</b>", cell_header)]]
    for ts in data["techStack"]:
        tech_rows.append([
            Paragraph(ts["tech"], cell_text),
            Paragraph(str(ts["count"]), cell_bold)
        ])
    tech_tbl = Table(tech_rows, colWidths=[190, 82])
    tech_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), c_primary),
        ('GRID', (0, 0), (-1, -1), 0.5, c_border),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, c_alt_row]),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))

    sub_tech_side = Table([[time_tbl, tech_tbl]], colWidths=[255, 277])
    sub_tech_side.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 0),
        ('RIGHTPADDING', (0, 0), (-1, -1), 0),
        ('TOPPADDING', (0, 0), (-1, -1), 0),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
    ]))
    story.append(sub_tech_side)
    story.append(Spacer(1, 14))

    # SECTION 5: Mentors & AI / Security
    story.append(make_section_banner("5. Mentorship, AI Co-Mentor & Infrastructure Health"))
    story.append(Spacer(1, 6))

    mentor_rows = [[
        Paragraph("<b>Rank</b>", cell_header),
        Paragraph("<b>Mentor Name</b>", cell_header),
        Paragraph("<b>Organization</b>", cell_header),
        Paragraph("<b>Sessions</b>", cell_header),
        Paragraph("<b>Rating</b>", cell_header)
    ]]
    for m in data["mentors"]:
        mentor_rows.append([
            Paragraph(m["rank"], cell_bold),
            Paragraph(m["name"], cell_text),
            Paragraph(m["company"], cell_text),
            Paragraph(str(m["sessions"]), cell_text),
            Paragraph(m["rating"], cell_bold)
        ])
    mentor_tbl = Table(mentor_rows, colWidths=[40, 160, 162, 80, 90])
    mentor_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), c_primary),
        ('GRID', (0, 0), (-1, -1), 0.5, c_border),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, c_alt_row]),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(mentor_tbl)
    story.append(Spacer(1, 10))

    # Summary box for AI, Certs & Security
    ai_sec = data["aiAndCerts"]
    sec = data["security"]
    infra_rows = [
        [
            Paragraph("<b>AI Queries Answered:</b>", meta_label), Paragraph(ai_sec["aiQueries"], meta_val),
            Paragraph("<b>AI Avg Latency:</b>", meta_label), Paragraph(ai_sec["avgAiLatency"], meta_val),
            Paragraph("<b>Certificates Minted:</b>", meta_label), Paragraph(ai_sec["certsMinted"], meta_val),
            Paragraph("<b>Certificates Revoked:</b>", meta_label), Paragraph(ai_sec["certsRevoked"], meta_val),
        ],
        [
            Paragraph("<b>Failed Login Audits:</b>", meta_label), Paragraph(sec["failedLogins"], meta_val),
            Paragraph("<b>Blocked IPs:</b>", meta_label), Paragraph(sec["blockedIps"], meta_val),
            Paragraph("<b>API Average Latency:</b>", meta_label), Paragraph(sec["avgApiLatency"], meta_val),
            Paragraph("<b>Server Live Uptime:</b>", meta_label), Paragraph(sec["serverUptime"], meta_val),
        ]
    ]
    infra_tbl = Table(infra_rows, colWidths=[100, 60, 100, 60, 100, 46, 90, 36])
    infra_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
        ('BOX', (0, 0), (-1, -1), 0.5, c_border),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(infra_tbl)

    # Build document with NumberedCanvas
    doc.build(story, canvasmaker=NumberedCanvas)
    return buffer.getvalue()


def generate_excel_bytes(data: dict) -> bytes:
    wb = openpyxl.Workbook()
    
    # Color palette
    dark_fill = PatternFill(start_color="0F172A", end_color="0F172A", fill_type="solid")
    primary_fill = PatternFill(start_color="0284C7", end_color="0284C7", fill_type="solid")
    alt_fill = PatternFill(start_color="F8FAFC", end_color="F8FAFC", fill_type="solid")
    meta_fill = PatternFill(start_color="F1F5F9", end_color="F1F5F9", fill_type="solid")

    title_font = Font(name="Calibri", size=16, bold=True, color="FFFFFF")
    sheet_header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    bold_font = Font(name="Calibri", size=10, bold=True, color="0F172A")
    regular_font = Font(name="Calibri", size=10, color="334155")
    meta_label_font = Font(name="Calibri", size=10, bold=True, color="0F172A")

    thin_border_side = Side(border_style="thin", color="E2E8F0")
    grid_border = Border(left=thin_border_side, right=thin_border_side, top=thin_border_side, bottom=thin_border_side)
    bottom_thick = Border(bottom=Side(border_style="medium", color="0284C7"))

    align_center = Alignment(horizontal="center", vertical="center")
    align_left = Alignment(horizontal="left", vertical="center")
    align_right = Alignment(horizontal="right", vertical="center")

    def auto_fit_columns(ws):
        for col in ws.columns:
            max_len = 0
            col_letter = get_column_letter(col[0].column)
            for cell in col:
                val = cell.value
                if val is not None:
                    # Ignore merged banner row lengths
                    if cell.row in [1, 2]:
                        continue
                    lines = str(val).split("\n")
                    for l in lines:
                        if len(l) > max_len:
                            max_len = len(l)
            ws.column_dimensions[col_letter].width = max(max_len + 4, 12)

    # -------------------------------------------------------------
    # SHEET 1: Executive Summary
    # -------------------------------------------------------------
    ws_summary = wb.active
    ws_summary.title = "Executive Summary"
    ws_summary.views.sheetView[0].showGridLines = True

    # Title Banner
    ws_summary.merge_cells("A1:F2")
    c = ws_summary["A1"]
    c.value = "HACKZEN CENTRAL PLATFORM INTELLIGENCE REPORT"
    c.font = title_font
    c.fill = dark_fill
    c.alignment = align_center

    # Metadata Block
    meta = data["metadata"]
    meta_rows = [
        ("Report Title:", meta["title"], "Generated At:", meta["generatedAt"]),
        ("Date Range:", meta["dateRange"], "Hackathon Scope:", meta["hackathon"]),
        ("College Scope:", meta["college"], "Role Scope:", meta["role"])
    ]
    for r_idx, (l1, v1, l2, v2) in enumerate(meta_rows, start=4):
        ws_summary.cell(row=r_idx, column=1, value=l1).font = meta_label_font
        ws_summary.cell(row=r_idx, column=2, value=v1).font = regular_font
        ws_summary.cell(row=r_idx, column=4, value=l2).font = meta_label_font
        ws_summary.cell(row=r_idx, column=5, value=v2).font = regular_font
        for col_idx in [1, 2, 4, 5]:
            cell = ws_summary.cell(row=r_idx, column=col_idx)
            cell.fill = meta_fill
            cell.border = grid_border

    # KPI Table on Executive Summary
    start_row = 8
    ws_summary.cell(row=start_row, column=1, value="Core Platform Key Performance Indicators").font = Font(name="Calibri", size=13, bold=True, color="0F172A")
    start_row += 1

    headers = ["Metric / Performance Indicator", "Current Value", "Variance / Trend", "Health Status"]
    for col_idx, h in enumerate(headers, start=1):
        cell = ws_summary.cell(row=start_row, column=col_idx, value=h)
        cell.font = sheet_header_font
        cell.fill = primary_fill
        cell.alignment = align_center if col_idx > 1 else align_left
        cell.border = grid_border

    start_row += 1
    for i, item in enumerate(data["kpis"]):
        row_num = start_row + i
        c1 = ws_summary.cell(row=row_num, column=1, value=item["metric"])
        c2 = ws_summary.cell(row=row_num, column=2, value=item["val"])
        c3 = ws_summary.cell(row=row_num, column=3, value=item["change"])
        c4 = ws_summary.cell(row=row_num, column=4, value=item["status"])

        c1.font = bold_font
        c2.font = regular_font
        c3.font = regular_font
        c4.font = bold_font

        c1.alignment = align_left
        c2.alignment = align_center
        c3.alignment = align_center
        c4.alignment = align_center

        row_fill = alt_fill if i % 2 == 1 else PatternFill(fill_type=None)
        for c in [c1, c2, c3, c4]:
            if i % 2 == 1:
                c.fill = row_fill
            c.border = grid_border

    auto_fit_columns(ws_summary)
    ws_summary.freeze_panes = "A10"

    # -------------------------------------------------------------
    # SHEET 2: Hackathons
    # -------------------------------------------------------------
    ws_hacks = wb.create_sheet(title="Hackathon Leaderboard")
    ws_hacks.views.sheetView[0].showGridLines = True

    ws_hacks.merge_cells("A1:E2")
    c = ws_hacks["A1"]
    c.value = "HACKATHON EVENTS & COMPLETION LEADERBOARD"
    c.font = title_font
    c.fill = dark_fill
    c.alignment = align_center

    h_headers = ["Rank", "Hackathon Event Title", "Total Registered Participants", "Submissions Received", "Project Completion Rate"]
    for col_idx, h in enumerate(h_headers, start=1):
        cell = ws_hacks.cell(row=4, column=col_idx, value=h)
        cell.font = sheet_header_font
        cell.fill = primary_fill
        cell.alignment = align_center if col_idx != 2 else align_left
        cell.border = grid_border

    for i, h in enumerate(data["hackathons"]):
        row_num = 5 + i
        c1 = ws_hacks.cell(row=row_num, column=1, value=h["rank"])
        c2 = ws_hacks.cell(row=row_num, column=2, value=h["name"])
        c3 = ws_hacks.cell(row=row_num, column=3, value=h["participants"])
        c4 = ws_hacks.cell(row=row_num, column=4, value=h["submissions"])
        c5 = ws_hacks.cell(row=row_num, column=5, value=h["completion"])

        c1.font = bold_font
        c2.font = regular_font
        c3.font = regular_font
        c4.font = regular_font
        c5.font = bold_font

        c1.alignment = align_center
        c2.alignment = align_left
        c3.alignment = align_center
        c4.alignment = align_center
        c5.alignment = align_center

        for cell in [c1, c2, c3, c4, c5]:
            if i % 2 == 1:
                cell.fill = alt_fill
            cell.border = grid_border

    auto_fit_columns(ws_hacks)
    ws_hacks.freeze_panes = "A5"

    # -------------------------------------------------------------
    # SHEET 3: User Demographics & Colleges
    # -------------------------------------------------------------
    ws_users = wb.create_sheet(title="Users & Institutions")
    ws_users.views.sheetView[0].showGridLines = True

    ws_users.merge_cells("A1:F2")
    c = ws_users["A1"]
    c.value = "USER DEMOGRAPHICS & INSTITUTIONAL PARTICIPATION"
    c.font = title_font
    c.fill = dark_fill
    c.alignment = align_center

    # Roles table
    ws_users.cell(row=4, column=1, value="Role Distribution").font = Font(name="Calibri", size=12, bold=True, color="0F172A")
    role_headers = ["User Role", "Percentage Share", "Total Count"]
    for col_idx, h in enumerate(role_headers, start=1):
        cell = ws_users.cell(row=5, column=col_idx, value=h)
        cell.font = sheet_header_font
        cell.fill = primary_fill
        cell.alignment = align_center if col_idx > 1 else align_left
        cell.border = grid_border

    for i, r in enumerate(data["roles"]):
        row_num = 6 + i
        c1 = ws_users.cell(row=row_num, column=1, value=r["role"])
        c2 = ws_users.cell(row=row_num, column=2, value=r["percentage"])
        c3 = ws_users.cell(row=row_num, column=3, value=r["count"])
        c1.font = bold_font
        c2.font = regular_font
        c3.font = regular_font
        c1.alignment = align_left
        c2.alignment = align_center
        c3.alignment = align_center
        for cell in [c1, c2, c3]:
            if i % 2 == 1:
                cell.fill = alt_fill
            cell.border = grid_border

    # Colleges table
    ws_users.cell(row=4, column=5, value="Top Participating Institutions").font = Font(name="Calibri", size=12, bold=True, color="0F172A")
    col_headers = ["Institution / College Name", "Registered Students"]
    for col_idx, h in enumerate(col_headers, start=5):
        cell = ws_users.cell(row=5, column=col_idx, value=h)
        cell.font = sheet_header_font
        cell.fill = primary_fill
        cell.alignment = align_left if col_idx == 5 else align_center
        cell.border = grid_border

    for i, col_item in enumerate(data["colleges"]):
        row_num = 6 + i
        c1 = ws_users.cell(row=row_num, column=5, value=col_item["college"])
        c2 = ws_users.cell(row=row_num, column=6, value=col_item["students"])
        c1.font = regular_font
        c2.font = bold_font
        c1.alignment = align_left
        c2.alignment = align_center
        for cell in [c1, c2]:
            if i % 2 == 1:
                cell.fill = alt_fill
            cell.border = grid_border

    auto_fit_columns(ws_users)

    # -------------------------------------------------------------
    # SHEET 4: Teams & Submissions
    # -------------------------------------------------------------
    ws_teams = wb.create_sheet(title="Teams & Tech Stacks")
    ws_teams.views.sheetView[0].showGridLines = True

    ws_teams.merge_cells("A1:F2")
    c = ws_teams["A1"]
    c.value = "SUBMISSION TIMELINE & POPULAR TECHNOLOGY STACKS"
    c.font = title_font
    c.fill = dark_fill
    c.alignment = align_center

    ws_teams.cell(row=4, column=1, value="Weekly Submission Milestones").font = Font(name="Calibri", size=12, bold=True, color="0F172A")
    t_headers = ["Timeline Phase", "Submissions Received", "Evaluations Completed"]
    for col_idx, h in enumerate(t_headers, start=1):
        cell = ws_teams.cell(row=5, column=col_idx, value=h)
        cell.font = sheet_header_font
        cell.fill = primary_fill
        cell.alignment = align_center if col_idx > 1 else align_left
        cell.border = grid_border

    for i, t in enumerate(data["timeline"]):
        row_num = 6 + i
        c1 = ws_teams.cell(row=row_num, column=1, value=t["week"])
        c2 = ws_teams.cell(row=row_num, column=2, value=t["submissions"])
        c3 = ws_teams.cell(row=row_num, column=3, value=t["evaluated"])
        c1.font = bold_font
        c2.font = regular_font
        c3.font = regular_font
        c1.alignment = align_left
        c2.alignment = align_center
        c3.alignment = align_center
        for cell in [c1, c2, c3]:
            if i % 2 == 1:
                cell.fill = alt_fill
            cell.border = grid_border

    ws_teams.cell(row=4, column=5, value="Project Technology Breakdown").font = Font(name="Calibri", size=12, bold=True, color="0F172A")
    tech_headers = ["Technology / Framework", "Active Project Count"]
    for col_idx, h in enumerate(tech_headers, start=5):
        cell = ws_teams.cell(row=5, column=col_idx, value=h)
        cell.font = sheet_header_font
        cell.fill = primary_fill
        cell.alignment = align_left if col_idx == 5 else align_center
        cell.border = grid_border

    for i, ts in enumerate(data["techStack"]):
        row_num = 6 + i
        c1 = ws_teams.cell(row=row_num, column=5, value=ts["tech"])
        c2 = ws_teams.cell(row=row_num, column=6, value=ts["count"])
        c1.font = regular_font
        c2.font = bold_font
        c1.alignment = align_left
        c2.alignment = align_center
        for cell in [c1, c2]:
            if i % 2 == 1:
                cell.fill = alt_fill
            cell.border = grid_border

    auto_fit_columns(ws_teams)

    # -------------------------------------------------------------
    # SHEET 5: Mentors, AI & Security
    # -------------------------------------------------------------
    ws_mentors = wb.create_sheet(title="Mentors & Infrastructure")
    ws_mentors.views.sheetView[0].showGridLines = True

    ws_mentors.merge_cells("A1:E2")
    c = ws_mentors["A1"]
    c.value = "MENTOR ENGAGEMENT, AI AUDIT & SYSTEM PERFORMANCE"
    c.font = title_font
    c.fill = dark_fill
    c.alignment = align_center

    ws_mentors.cell(row=4, column=1, value="Top Mentors Leaderboard").font = Font(name="Calibri", size=12, bold=True, color="0F172A")
    m_headers = ["Rank", "Mentor Name", "Organization / Affiliation", "Sessions Hosted", "Average Rating"]
    for col_idx, h in enumerate(m_headers, start=1):
        cell = ws_mentors.cell(row=5, column=col_idx, value=h)
        cell.font = sheet_header_font
        cell.fill = primary_fill
        cell.alignment = align_center if col_idx != 2 and col_idx != 3 else align_left
        cell.border = grid_border

    for i, m in enumerate(data["mentors"]):
        row_num = 6 + i
        c1 = ws_mentors.cell(row=row_num, column=1, value=m["rank"])
        c2 = ws_mentors.cell(row=row_num, column=2, value=m["name"])
        c3 = ws_mentors.cell(row=row_num, column=3, value=m["company"])
        c4 = ws_mentors.cell(row=row_num, column=4, value=m["sessions"])
        c5 = ws_mentors.cell(row=row_num, column=5, value=m["rating"])

        c1.font = bold_font
        c2.font = regular_font
        c3.font = regular_font
        c4.font = regular_font
        c5.font = bold_font

        c1.alignment = align_center
        c2.alignment = align_left
        c3.alignment = align_left
        c4.alignment = align_center
        c5.alignment = align_center

        for cell in [c1, c2, c3, c4, c5]:
            if i % 2 == 1:
                cell.fill = alt_fill
            cell.border = grid_border

    # AI & Security Audit Table
    start_row = 12
    ws_mentors.cell(row=start_row, column=1, value="AI Co-Mentor & Infrastructure Health Audit").font = Font(name="Calibri", size=12, bold=True, color="0F172A")
    start_row += 1

    audit_headers = ["Metric / Audit Parameter", "Value", "Metric / Audit Parameter", "Value"]
    for col_idx, h in enumerate(audit_headers, start=1):
        cell = ws_mentors.cell(row=start_row, column=col_idx, value=h)
        cell.font = sheet_header_font
        cell.fill = primary_fill
        cell.alignment = align_left
        cell.border = grid_border

    start_row += 1
    ai_sec = data["aiAndCerts"]
    sec = data["security"]
    audit_data = [
        ("AI Queries Answered", ai_sec["aiQueries"], "Failed Login Audits", sec["failedLogins"]),
        ("AI Unique Users", ai_sec["uniqueAiUsers"], "Suspended / Blocked Accounts", sec["blockedIps"]),
        ("AI Co-Mentor Avg Latency", ai_sec["avgAiLatency"], "Core API Avg Latency", sec["avgApiLatency"]),
        ("AI Helpful Rating", ai_sec["aiHelpfulRate"], "Server CPU Load", sec["cpuLoad"]),
        ("Certificates Minted", ai_sec["certsMinted"], "Server Memory Allocation", sec["memoryUsage"]),
        ("Certificates Verified", ai_sec["certsVerified"], "Live Platform Uptime", sec["serverUptime"]),
    ]

    for i, (k1, v1, k2, v2) in enumerate(audit_data):
        row_num = start_row + i
        c1 = ws_mentors.cell(row=row_num, column=1, value=k1)
        c2 = ws_mentors.cell(row=row_num, column=2, value=v1)
        c3 = ws_mentors.cell(row=row_num, column=3, value=k2)
        c4 = ws_mentors.cell(row=row_num, column=4, value=v2)

        c1.font = bold_font
        c2.font = regular_font
        c3.font = bold_font
        c4.font = regular_font

        c1.alignment = align_left
        c2.alignment = align_center
        c3.alignment = align_left
        c4.alignment = align_center

        for cell in [c1, c2, c3, c4]:
            if i % 2 == 1:
                cell.fill = alt_fill
            cell.border = grid_border

    auto_fit_columns(ws_mentors)

    out_buf = io.BytesIO()
    wb.save(out_buf)
    return out_buf.getvalue()


if __name__ == "__main__":
    data = build_sample_data()
    print("Generating PDF...")
    pdf_bytes = generate_pdf_bytes(data)
    print(f"PDF generated successfully! Size: {len(pdf_bytes)} bytes")
    with open("scratch/test_report.pdf", "wb") as f:
        f.write(pdf_bytes)

    print("Generating Excel...")
    excel_bytes = generate_excel_bytes(data)
    print(f"Excel generated successfully! Size: {len(excel_bytes)} bytes")
    with open("scratch/test_report.xlsx", "wb") as f:
        f.write(excel_bytes)
    print("ALL TESTS PASSED!")
